INSERT INTO PAIS (BANDEIRA_URL_IMAGEM, capital, continente, nome) VALUES
('https://flagcdn.com/w320/ar.png', 'Buenos Aires', 'America do Sul', 'Argentina'),
('https://flagcdn.com/w320/cl.png', 'Santiago', 'America do Sul', 'Chile'),
('https://flagcdn.com/w320/pe.png', 'Lima', 'America do Sul', 'Peru'),
('https://flagcdn.com/w320/co.png', 'Bogotá', 'America do Sul', 'Colômbia'),
('https://flagcdn.com/w320/ve.png', 'Caracas', 'America do Sul', 'Venezuela'),
('https://flagcdn.com/w320/uy.png', 'Montevidéu', 'America do Sul', 'Uruguai'),
('https://flagcdn.com/w320/mx.png', 'Cidade do México', 'America do Norte', 'México'),
('https://flagcdn.com/w320/us.png', 'Washington, D.C.', 'America do Norte', 'Estados Unidos'),
('https://flagcdn.com/w320/ca.png', 'Ottawa', 'America do Norte', 'Canadá'),
('https://flagcdn.com/w320/es.png', 'Madri', 'Europa', 'Espanha'),
('https://flagcdn.com/w320/pt.png', 'Lisboa', 'Europa', 'Portugal'),
('https://flagcdn.com/w320/fr.png', 'Paris', 'Europa', 'França'),
('https://flagcdn.com/w320/de.png', 'Berlim', 'Europa', 'Alemanha'),
('https://flagcdn.com/w320/it.png', 'Roma', 'Europa', 'Itália'),
('https://flagcdn.com/w320/gb.png', 'Londres', 'Europa', 'Reino Unido'),
('https://flagcdn.com/w320/br.png', 'Brasília', 'America do Sul', 'Brasil'),
('https://flagcdn.com/w320/ru.png', 'Moscou', 'Europa/Ásia', 'Rússia'),
('https://flagcdn.com/w320/cn.png', 'Pequim', 'Ásia', 'China'),
('https://flagcdn.com/w320/jp.png', 'Tóquio', 'Ásia', 'Japão'),
('https://flagcdn.com/w320/in.png', 'Nova Délhi', 'Ásia', 'Índia'),
('https://flagcdn.com/w320/th.png', 'Bangcoc', 'Ásia', 'Tailândia'),
('https://flagcdn.com/w320/kr.png', 'Seul', 'Ásia', 'Coreia do Sul'),
('https://flagcdn.com/w320/id.png', 'Jacarta', 'Ásia', 'Indonésia'),
('https://flagcdn.com/w320/za.png', 'Pretória', 'África', 'África do Sul'),
('https://flagcdn.com/w320/eg.png', 'Cairo', 'África', 'Egito'),
('https://flagcdn.com/w320/ke.png', 'Nairobi', 'África', 'Quênia'),
('https://flagcdn.com/w320/ng.png', 'Lagos', 'África', 'Nigéria'),
('https://flagcdn.com/w320/au.png', 'Camberra', 'Oceania', 'Austrália'),
('https://flagcdn.com/w320/nz.png', 'Wellington', 'Oceania', 'Nova Zelândia'),
('https://flagcdn.com/w320/fj.png', 'Suva', 'Oceania', 'Fiji');
